### ISSUE TITLE
Layouts

### ISSUE THREAD

**Issue by virones** [stefanwalther/sense-themable-kpi-tile#1]
Hi, 

I  can't change colours or create new styles. Fiirst, I had change layouts.json. in src/config. After that, I try to refresh Qlik Sense App, but I don't see my changes. 

Would you help me?

**Comment by Chricky** [comment]
When you are in your Qlik Sense Sheet, press "ctrl+shift+right click" and then "show dev tools". Go to Tab Network and make sure you mark "disable cache". So as long as the dev tools are open you can reload your sheet and it will refresh as soon as you do that.

Regards
Chris

**Comment by virones** [comment]
It works. Thanks. 

PD: The code  file to change is in \Qlik\Sense\Extensions\sense-themable-kpi-tile-master\build\dev\config
